package com.daymark.synccrypto

import com.goterl.lazysodium.LazySodium
import com.goterl.lazysodium.interfaces.AEAD
import com.goterl.lazysodium.interfaces.KeyDerivation
import com.goterl.lazysodium.interfaces.PwHash
import com.goterl.lazysodium.interfaces.Sign
import com.sun.jna.NativeLong
import java.util.Base64

/**
 * Daymark Companion sync crypto — the Kotlin mirror of the reference implementation in
 * `companion/web/src/lib/sync/crypto.ts`. MUST produce byte-identical output; see
 * `docs/SYNC_PROTOCOL.md` for the normative wire format this implements.
 *
 * Contract (per docs/COMPANION_SECURITY.md §4):
 *   passphrase --Argon2id(salt, mem>=256MiB, ops>=3)--> master(32)
 *   master --crypto_kdf(ctx="dmsync01")--+- id 1 -> SYNC_KEY        (XChaCha20-Poly1305)
 *                                         +- id 2 -> MANIFEST_SEED   (Ed25519 signing seed)
 *   snapshot blob = MAGIC("DMS1") | FMT | nonce(24) | XChaCha20Poly1305(body, AAD, nonce, SYNC_KEY)
 *     FMT 0x02, the only format written:  body = pad(plaintext)   AAD = utf8("daymark.snapshot.v2|" + lineage + "|" + version)
 *     FMT 0x01, still read, never written: body = plaintext        AAD = utf8("daymark.snapshot.v1|" + lineage + "|" + version)
 *
 * Padded snapshots (#315, #316): a snapshot is padded by [Padding] before it is encrypted, so the
 * stored size says which size bucket it falls in and not how much was written between two syncs.
 * The server still sees when each version arrives. The format byte sits outside the ciphertext,
 * where the server can change it, so each format also names itself in the associated data: a
 * relabelled envelope fails to open instead of opening in the wrong form. Unpadding runs only
 * after the AEAD has authenticated the body, and it is strict. Format 1 is opened and never
 * written: every snapshot stored before #315 is in it.
 *
 * [sodium] is typed as the shared abstract `com.goterl.lazysodium.LazySodium` base class,
 * which both `lazysodium-java` (LazySodiumJava, used by this module's own unit tests — real
 * native crypto on the plain JVM, no Android SDK needed) and `lazysodium-android`
 * (LazySodiumAndroid, used by the real `sync` product flavor at runtime) extend identically.
 * That cross-artifact parity is enforced by LazySodiumParityTest, which parses both artifacts'
 * bytecode on every test run and resolves this class's own compiled references against the
 * android copy — it is checked, not assumed, because the assumed version of it was measured
 * false at 5.1.0 (java lacked the entire Ristretto255 surface the android artifact carried).
 * Every primitive below is additionally cross-checked against the TS reference (see
 * SyncCryptoTest's conformance vectors, generated by running the actual `crypto.ts` reference
 * against fixed inputs).
 */
class SyncCrypto(private val sodium: LazySodium) {

    class SyncCryptoException(message: String) : Exception(message)

    class KdfParams(val memMiB: Int, val ops: Int) {
        companion object {
            /** Meets the security doc's floor (>=256 MiB, >=3 ops). */
            val DEFAULT = KdfParams(memMiB = 256, ops = 3)
        }
    }

    class OwnerKeys(val syncKey: ByteArray, val manifestSeed: ByteArray)

    data class ManifestEntry(val version: Long, val hash: String)
    data class Manifest(val lineage: String, val head: Long, val entries: List<ManifestEntry>)
    data class SignedManifest(val signatureB64: String, val publicKeyB64: String)

    /** 16-byte random KDF salt (non-secret; published in keyparams). */
    fun newSalt(): ByteArray = sodium.randomBytesBuf(PwHash.SALTBYTES)

    /** passphrase + salt + params -> master -> purpose-separated subkeys. */
    fun deriveKeys(passphrase: String, salt: ByteArray, params: KdfParams = KdfParams.DEFAULT): OwnerKeys {
        val passwordBytes = passphrase.toByteArray(Charsets.UTF_8)
        val master = ByteArray(KeyDerivation.MASTER_KEY_BYTES)
        val memLimit = NativeLong(params.memMiB.toLong() * 1024 * 1024)
        val ok = sodium.cryptoPwHash(
            master, master.size, passwordBytes, passwordBytes.size, salt,
            params.ops.toLong(), memLimit, PwHash.Alg.PWHASH_ALG_ARGON2ID13,
        )
        if (!ok) throw SyncCryptoException("Argon2id key derivation failed")

        val syncKey = deriveSubkey(master, SUBKEY_SYNC, AEAD.XCHACHA20POLY1305_IETF_KEYBYTES)
        val manifestSeed = deriveSubkey(master, SUBKEY_MANIFEST, Sign.SEEDBYTES)
        return OwnerKeys(syncKey, manifestSeed)
    }

    private fun deriveSubkey(master: ByteArray, subkeyId: Long, subkeyLen: Int): ByteArray {
        val subkey = ByteArray(subkeyLen)
        val rc = sodium.cryptoKdfDeriveFromKey(subkey, subkey.size, subkeyId, KDF_CONTEXT, master)
        if (rc != 0) throw SyncCryptoException("crypto_kdf_derive_from_key failed (id=$subkeyId)")
        return subkey
    }

    /**
     * plaintext (e.g. a BackupData JSON, UTF-8) -> opaque envelope bytes for the server, padded
     * (format 2), `snapshotBlobLength(plaintext.size)` bytes long.
     */
    fun encryptSnapshot(plaintext: ByteArray, syncKey: ByteArray, lineage: String, version: Long): ByteArray =
        sealSnapshot(plaintext, syncKey, lineage, version, sodium.randomBytesBuf(NONCE_BYTES))

    /**
     * [encryptSnapshot] under a nonce the caller supplies, so the writer itself can be held to the
     * web's conformance vector. Not public: a nonce used twice under one key breaks
     * XChaCha20-Poly1305, and production draws a fresh one for every snapshot.
     */
    internal fun sealSnapshot(plaintext: ByteArray, syncKey: ByteArray, lineage: String, version: Long, nonce: ByteArray): ByteArray {
        if (nonce.size != NONCE_BYTES) throw SyncCryptoException("nonce must be $NONCE_BYTES bytes")
        val body = try {
            Padding.pad(plaintext)
        } catch (_: Padding.PaddingException) {
            throw SyncCryptoException("snapshot too large to pad")
        }
        val aad = aad(FMT_PADDED, lineage, version)
        val cipher = ByteArray(body.size + TAG_BYTES)
        val cipherLen = LongArray(1)
        val ok = sodium.cryptoAeadXChaCha20Poly1305IetfEncrypt(
            cipher, cipherLen, body, body.size.toLong(),
            aad, aad.size.toLong(), null, nonce, syncKey,
        )
        if (!ok) throw SyncCryptoException("AEAD encryption failed")

        val out = ByteArray(HEADER_BYTES + cipherLen[0].toInt())
        var offset = 0
        MAGIC.copyInto(out, offset); offset += MAGIC.size
        out[offset] = FMT_PADDED; offset += 1
        nonce.copyInto(out, offset); offset += nonce.size
        cipher.copyInto(out, offset, 0, cipherLen[0].toInt())
        return out
    }

    /**
     * Opaque envelope bytes -> plaintext, from either format. Throws if tampered, wrong key, wrong
     * lineage/version, or the format byte was changed (the associated data names the format).
     */
    fun decryptSnapshot(envelope: ByteArray, syncKey: ByteArray, lineage: String, version: Long): ByteArray {
        if (envelope.size < HEADER_BYTES) throw SyncCryptoException("envelope too short")
        for (i in MAGIC.indices) {
            if (envelope[i] != MAGIC[i]) throw SyncCryptoException("bad magic — not a Daymark snapshot envelope")
        }
        val format = envelope[MAGIC.size]
        if (format != FMT_PADDED && format != FMT_UNPADDED) {
            throw SyncCryptoException("unsupported envelope format ${format.toInt() and 0xff}")
        }
        val nonce = envelope.copyOfRange(MAGIC.size + 1, HEADER_BYTES)
        val cipher = envelope.copyOfRange(HEADER_BYTES, envelope.size)
        if (cipher.size < TAG_BYTES) throw SyncCryptoException("envelope too short")

        val aad = aad(format, lineage, version)
        val opened = ByteArray(cipher.size - TAG_BYTES)
        val openedLen = LongArray(1)
        val ok = sodium.cryptoAeadXChaCha20Poly1305IetfDecrypt(
            opened, openedLen, null, cipher, cipher.size.toLong(),
            aad, aad.size.toLong(), nonce, syncKey,
        )
        if (!ok) throw SyncCryptoException("decryption failed — tampered, wrong key, or wrong lineage/version")
        val body = if (openedLen[0].toInt() == opened.size) opened else opened.copyOf(openedLen[0].toInt())
        if (format == FMT_UNPADDED) return body
        // Only an authenticated body reaches here, so a padding refusal is never about tampering:
        // it means the writer that holds the sync key padded wrongly.
        return try {
            Padding.unpad(body)
        } catch (_: Padding.PaddingException) {
            throw SyncCryptoException("snapshot opened, but its padding is not in the standard form")
        }
    }

    /** SHA-256 hex over arbitrary bytes (matches the server's X-Content-Hash). */
    fun sha256Hex(bytes: ByteArray): String {
        val out = ByteArray(32)
        val ok = sodium.cryptoHashSha256(out, bytes, bytes.size.toLong())
        if (!ok) throw SyncCryptoException("SHA-256 failed")
        return out.joinToString("") { "%02x".format(it) }
    }

    fun signManifest(manifest: Manifest, manifestSeed: ByteArray): SignedManifest {
        val (publicKey, secretKey) = deriveSignKeypair(manifestSeed)
        val message = manifestBytes(manifest)
        val signature = ByteArray(Sign.BYTES)
        if (!sodium.cryptoSignDetached(signature, message, message.size.toLong(), secretKey)) {
            throw SyncCryptoException("manifest signing failed")
        }
        return SignedManifest(signatureB64 = toBase64(signature), publicKeyB64 = toBase64(publicKey))
    }

    fun verifyManifest(manifest: Manifest, signatureB64: String, publicKeyB64: String): Boolean {
        val signature = fromBase64(signatureB64)
        val publicKey = fromBase64(publicKeyB64)
        if (signature.size != Sign.BYTES || publicKey.size != Sign.PUBLICKEYBYTES) return false
        val message = manifestBytes(manifest)
        return sodium.cryptoSignVerifyDetached(signature, message, message.size, publicKey)
    }

    /** The Ed25519 public key the owner's passphrase implies (readers re-derive + compare). */
    fun manifestPublicKeyB64(manifestSeed: ByteArray): String = toBase64(deriveSignKeypair(manifestSeed).first)

    private fun deriveSignKeypair(manifestSeed: ByteArray): Pair<ByteArray, ByteArray> {
        val publicKey = ByteArray(Sign.PUBLICKEYBYTES)
        val secretKey = ByteArray(Sign.SECRETKEYBYTES)
        if (!sodium.cryptoSignSeedKeypair(publicKey, secretKey, manifestSeed)) {
            throw SyncCryptoException("Ed25519 keypair derivation failed")
        }
        return publicKey to secretKey
    }

    companion object {
        val MAGIC = byteArrayOf(0x44, 0x4D, 0x53, 0x31) // "DMS1"

        /** The unpadded format of every snapshot stored before #315. Opened, never written. */
        const val FMT_UNPADDED: Byte = 0x01

        /** The padded format (#315): the only one [encryptSnapshot] writes. */
        const val FMT_PADDED: Byte = 0x02

        // Fixed by the algorithm (crypto_aead_xchacha20poly1305_ietf_NPUBBYTES and _ABYTES).
        private const val NONCE_BYTES = AEAD.XCHACHA20POLY1305_IETF_NPUBBYTES
        private const val TAG_BYTES = AEAD.XCHACHA20POLY1305_IETF_ABYTES
        private val HEADER_BYTES = MAGIC.size + 1 + NONCE_BYTES

        /** The u32 length prefix [Padding] puts in front of the plaintext (its layout). */
        private const val PAD_PREFIX_BYTES = 4

        private val KDF_CONTEXT = "dmsync01".toByteArray(Charsets.UTF_8) // exactly 8 bytes
        private const val SUBKEY_SYNC = 1L
        private const val SUBKEY_MANIFEST = 2L

        /** Each format's name in the associated data, so the format byte cannot be changed on its own. */
        private fun aad(format: Byte, lineage: String, version: Long): ByteArray {
            val context = when (format) {
                FMT_PADDED -> "daymark.snapshot.v2"
                FMT_UNPADDED -> "daymark.snapshot.v1"
                else -> throw SyncCryptoException("unsupported envelope format ${format.toInt() and 0xff}")
            }
            return "$context|$lineage|$version".toByteArray(Charsets.UTF_8)
        }

        /**
         * The size of the blob [encryptSnapshot] writes for a plaintext of [plaintextLength] bytes:
         * the header, the padded body and the tag. Needs no libsodium, so a writer can check a
         * snapshot against the server's size limit before it derives a key or sends anything.
         */
        fun snapshotBlobLength(plaintextLength: Long): Long {
            require(plaintextLength >= 0) { "snapshotBlobLength: bad length $plaintextLength" }
            return HEADER_BYTES + Padding.paddedLength(PAD_PREFIX_BYTES + plaintextLength) + TAG_BYTES
        }

        /**
         * All base64 in the protocol is RFC 4648 §5 URL-safe, NO padding. Deliberately uses
         * plain [java.util.Base64] — NOT lazysodium's own base64 facade, which only wraps the
         * *standard* (`+`/`/`, padded) alphabet and would silently break interop. See the
         * conformance vector in SyncCryptoTest / docs/SYNC_PROTOCOL.md §1.2.
         */
        fun toBase64(bytes: ByteArray): String = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)
        fun fromBase64(b64: String): ByteArray = Base64.getUrlDecoder().decode(b64)

        /** Canonical bytes a manifest is signed over (stable key order, matches JSON.stringify). */
        fun manifestBytes(manifest: Manifest): ByteArray {
            val entries = manifest.entries.joinToString(",") { entry ->
                "{\"version\":${entry.version},\"hash\":\"${jsonEscape(entry.hash)}\"}"
            }
            val json = "{\"lineage\":\"${jsonEscape(manifest.lineage)}\",\"head\":${manifest.head}," +
                "\"entries\":[$entries]}"
            return json.toByteArray(Charsets.UTF_8)
        }

        private fun jsonEscape(s: String): String {
            val sb = StringBuilder(s.length)
            for (c in s) {
                when (c) {
                    '"' -> sb.append("\\\"")
                    '\\' -> sb.append("\\\\")
                    '\n' -> sb.append("\\n")
                    '\r' -> sb.append("\\r")
                    '\t' -> sb.append("\\t")
                    '\b' -> sb.append("\\b")
                    '\u000C' -> sb.append("\\f")
                    else -> if (c.code < 0x20) sb.append("\\u%04x".format(c.code)) else sb.append(c)
                }
            }
            return sb.toString()
        }
    }
}
