package com.daymark.synccrypto

import com.goterl.lazysodium.LazySodium
import com.goterl.lazysodium.interfaces.AEAD
import com.goterl.lazysodium.interfaces.KeyDerivation
import com.goterl.lazysodium.interfaces.PwHash
import com.goterl.lazysodium.interfaces.Sign
import com.sun.jna.NativeLong
import java.util.Base64

/**
 * Daymark Companion sync crypto — the Kotlin mirror of the reference implementation in
 * `companion/web/src/lib/sync/crypto.ts`. MUST produce byte-identical output; see
 * `docs/SYNC_PROTOCOL.md` for the normative wire format this implements.
 *
 * Contract (per docs/COMPANION_SECURITY.md §4):
 *   passphrase --Argon2id(salt, mem>=256MiB, ops>=3)--> master(32)
 *   master --crypto_kdf(ctx="dmsync01")--+- id 1 -> SYNC_KEY        (XChaCha20-Poly1305)
 *                                         +- id 2 -> MANIFEST_SEED   (Ed25519 signing seed)
 *   snapshot blob = MAGIC("DMS1") | FMT(1) | nonce(24) | XChaCha20Poly1305(plaintext, AAD, nonce, SYNC_KEY)
 *   AAD = utf8("daymark.snapshot.v1|" + lineage + "|" + version)
 *
 * [sodium] is typed as the shared abstract `com.goterl.lazysodium.LazySodium` base class,
 * which both `lazysodium-java` (LazySodiumJava, used by this module's own unit tests — real
 * native crypto on the plain JVM, no Android SDK needed) and `lazysodium-android`
 * (LazySodiumAndroid, used by the real `sync` product flavor at runtime) extend identically.
 * That cross-artifact API parity is Terl's stated design goal for the two libraries and was
 * independently confirmed for this project by decompiling both AARs/jars and by cross-checking
 * every primitive below against the TS reference (see SyncCryptoTest's conformance vectors,
 * generated by running the actual `crypto.ts` reference against fixed inputs).
 */
class SyncCrypto(private val sodium: LazySodium) {

    class SyncCryptoException(message: String) : Exception(message)

    class KdfParams(val memMiB: Int, val ops: Int) {
        companion object {
            /** Meets the security doc's floor (>=256 MiB, >=3 ops). */
            val DEFAULT = KdfParams(memMiB = 256, ops = 3)
        }
    }

    class OwnerKeys(val syncKey: ByteArray, val manifestSeed: ByteArray)

    data class ManifestEntry(val version: Long, val hash: String)
    data class Manifest(val lineage: String, val head: Long, val entries: List<ManifestEntry>)
    data class SignedManifest(val signatureB64: String, val publicKeyB64: String)

    /** 16-byte random KDF salt (non-secret; published in keyparams). */
    fun newSalt(): ByteArray = sodium.randomBytesBuf(PwHash.SALTBYTES)

    /** passphrase + salt + params -> master -> purpose-separated subkeys. */
    fun deriveKeys(passphrase: String, salt: ByteArray, params: KdfParams = KdfParams.DEFAULT): OwnerKeys {
        val passwordBytes = passphrase.toByteArray(Charsets.UTF_8)
        val master = ByteArray(KeyDerivation.MASTER_KEY_BYTES)
        val memLimit = NativeLong(params.memMiB.toLong() * 1024 * 1024)
        val ok = sodium.cryptoPwHash(
            master, master.size, passwordBytes, passwordBytes.size, salt,
            params.ops.toLong(), memLimit, PwHash.Alg.PWHASH_ALG_ARGON2ID13,
        )
        if (!ok) throw SyncCryptoException("Argon2id key derivation failed")

        val syncKey = deriveSubkey(master, SUBKEY_SYNC, AEAD.XCHACHA20POLY1305_IETF_KEYBYTES)
        val manifestSeed = deriveSubkey(master, SUBKEY_MANIFEST, Sign.SEEDBYTES)
        return OwnerKeys(syncKey, manifestSeed)
    }

    private fun deriveSubkey(master: ByteArray, subkeyId: Long, subkeyLen: Int): ByteArray {
        val subkey = ByteArray(subkeyLen)
        val rc = sodium.cryptoKdfDeriveFromKey(subkey, subkey.size, subkeyId, KDF_CONTEXT, master)
        if (rc != 0) throw SyncCryptoException("crypto_kdf_derive_from_key failed (id=$subkeyId)")
        return subkey
    }

    /** plaintext (e.g. a BackupData JSON, UTF-8) -> opaque envelope bytes for the server. */
    fun encryptSnapshot(plaintext: ByteArray, syncKey: ByteArray, lineage: String, version: Long): ByteArray {
        val nonce = sodium.randomBytesBuf(AEAD.XCHACHA20POLY1305_IETF_NPUBBYTES)
        val aad = aad(lineage, version)
        val cipher = ByteArray(plaintext.size + AEAD.XCHACHA20POLY1305_IETF_ABYTES)
        val cipherLen = LongArray(1)
        val ok = sodium.cryptoAeadXChaCha20Poly1305IetfEncrypt(
            cipher, cipherLen, plaintext, plaintext.size.toLong(),
            aad, aad.size.toLong(), null, nonce, syncKey,
        )
        if (!ok) throw SyncCryptoException("AEAD encryption failed")

        val out = ByteArray(MAGIC.size + 1 + nonce.size + cipherLen[0].toInt())
        var offset = 0
        MAGIC.copyInto(out, offset); offset += MAGIC.size
        out[offset] = FMT; offset += 1
        nonce.copyInto(out, offset); offset += nonce.size
        cipher.copyInto(out, offset, 0, cipherLen[0].toInt())
        return out
    }

    /** Opaque envelope bytes -> plaintext. Throws if tampered, wrong key, or wrong lineage/version. */
    fun decryptSnapshot(envelope: ByteArray, syncKey: ByteArray, lineage: String, version: Long): ByteArray {
        val nb = AEAD.XCHACHA20POLY1305_IETF_NPUBBYTES
        val headerLen = MAGIC.size + 1 + nb
        if (envelope.size < headerLen) throw SyncCryptoException("envelope too short")
        for (i in MAGIC.indices) {
            if (envelope[i] != MAGIC[i]) throw SyncCryptoException("bad magic — not a Daymark snapshot envelope")
        }
        if (envelope[MAGIC.size] != FMT) {
            throw SyncCryptoException("unsupported envelope format ${envelope[MAGIC.size]}")
        }
        val nonce = envelope.copyOfRange(MAGIC.size + 1, headerLen)
        val cipher = envelope.copyOfRange(headerLen, envelope.size)
        if (cipher.size < AEAD.XCHACHA20POLY1305_IETF_ABYTES) throw SyncCryptoException("envelope too short")

        val aad = aad(lineage, version)
        val plaintext = ByteArray(cipher.size - AEAD.XCHACHA20POLY1305_IETF_ABYTES)
        val plaintextLen = LongArray(1)
        val ok = sodium.cryptoAeadXChaCha20Poly1305IetfDecrypt(
            plaintext, plaintextLen, null, cipher, cipher.size.toLong(),
            aad, aad.size.toLong(), nonce, syncKey,
        )
        if (!ok) throw SyncCryptoException("decryption failed — tampered, wrong key, or wrong lineage/version")
        return if (plaintextLen[0].toInt() == plaintext.size) plaintext else plaintext.copyOf(plaintextLen[0].toInt())
    }

    /** SHA-256 hex over arbitrary bytes (matches the server's X-Content-Hash). */
    fun sha256Hex(bytes: ByteArray): String {
        val out = ByteArray(32)
        val ok = sodium.cryptoHashSha256(out, bytes, bytes.size.toLong())
        if (!ok) throw SyncCryptoException("SHA-256 failed")
        return out.joinToString("") { "%02x".format(it) }
    }

    fun signManifest(manifest: Manifest, manifestSeed: ByteArray): SignedManifest {
        val (publicKey, secretKey) = deriveSignKeypair(manifestSeed)
        val message = manifestBytes(manifest)
        val signature = ByteArray(Sign.BYTES)
        if (!sodium.cryptoSignDetached(signature, message, message.size.toLong(), secretKey)) {
            throw SyncCryptoException("manifest signing failed")
        }
        return SignedManifest(signatureB64 = toBase64(signature), publicKeyB64 = toBase64(publicKey))
    }

    fun verifyManifest(manifest: Manifest, signatureB64: String, publicKeyB64: String): Boolean {
        val signature = fromBase64(signatureB64)
        val publicKey = fromBase64(publicKeyB64)
        if (signature.size != Sign.BYTES || publicKey.size != Sign.PUBLICKEYBYTES) return false
        val message = manifestBytes(manifest)
        return sodium.cryptoSignVerifyDetached(signature, message, message.size, publicKey)
    }

    /** The Ed25519 public key the owner's passphrase implies (readers re-derive + compare). */
    fun manifestPublicKeyB64(manifestSeed: ByteArray): String = toBase64(deriveSignKeypair(manifestSeed).first)

    private fun deriveSignKeypair(manifestSeed: ByteArray): Pair<ByteArray, ByteArray> {
        val publicKey = ByteArray(Sign.PUBLICKEYBYTES)
        val secretKey = ByteArray(Sign.SECRETKEYBYTES)
        if (!sodium.cryptoSignSeedKeypair(publicKey, secretKey, manifestSeed)) {
            throw SyncCryptoException("Ed25519 keypair derivation failed")
        }
        return publicKey to secretKey
    }

    companion object {
        val MAGIC = byteArrayOf(0x44, 0x4D, 0x53, 0x31) // "DMS1"
        const val FMT: Byte = 0x01

        private val KDF_CONTEXT = "dmsync01".toByteArray(Charsets.UTF_8) // exactly 8 bytes
        private const val SUBKEY_SYNC = 1L
        private const val SUBKEY_MANIFEST = 2L

        fun aad(lineage: String, version: Long): ByteArray =
            "daymark.snapshot.v1|$lineage|$version".toByteArray(Charsets.UTF_8)

        /**
         * All base64 in the protocol is RFC 4648 §5 URL-safe, NO padding. Deliberately uses
         * plain [java.util.Base64] — NOT lazysodium's own base64 facade, which only wraps the
         * *standard* (`+`/`/`, padded) alphabet and would silently break interop. See the
         * conformance vector in SyncCryptoTest / docs/SYNC_PROTOCOL.md §1.2.
         */
        fun toBase64(bytes: ByteArray): String = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)
        fun fromBase64(b64: String): ByteArray = Base64.getUrlDecoder().decode(b64)

        /** Canonical bytes a manifest is signed over (stable key order, matches JSON.stringify). */
        fun manifestBytes(manifest: Manifest): ByteArray {
            val entries = manifest.entries.joinToString(",") { entry ->
                "{\"version\":${entry.version},\"hash\":\"${jsonEscape(entry.hash)}\"}"
            }
            val json = "{\"lineage\":\"${jsonEscape(manifest.lineage)}\",\"head\":${manifest.head}," +
                "\"entries\":[$entries]}"
            return json.toByteArray(Charsets.UTF_8)
        }

        private fun jsonEscape(s: String): String {
            val sb = StringBuilder(s.length)
            for (c in s) {
                when (c) {
                    '"' -> sb.append("\\\"")
                    '\\' -> sb.append("\\\\")
                    '\n' -> sb.append("\\n")
                    '\r' -> sb.append("\\r")
                    '\t' -> sb.append("\\t")
                    '\b' -> sb.append("\\b")
                    '\u000C' -> sb.append("\\f")
                    else -> if (c.code < 0x20) sb.append("\\u%04x".format(c.code)) else sb.append(c)
                }
            }
            return sb.toString()
        }
    }
}
