package com.daymark.app.security

import java.security.SecureRandom

/*
 * THE RECOVERY CODE — the second secret that opens this phone's data key, built to be written on
 * paper by a frightened person and read back, correctly, months later by the same person.
 *
 * ─── THIS IS A PORT, AND THE ORIGINAL IS THE SPECIFICATION ──────────────────────────────────────
 *
 * `companion/web/src/lib/recovery/recoveryCode.ts` is the original and carries the full argument:
 * why 31 symbols and not a round 32, why 0/O/1/I/L are dropped from the alphabet rather than folded
 * into it the way Crockford's base32 does, why the check symbol is a weighted sum mod a PRIME, and
 * why the module detects errors without ever offering to correct one. Read that file for the
 * reasoning. This file is the same arithmetic in Kotlin, and `RecoveryCodeParityTest` pins it to
 * fixed vectors generated by running the TypeScript module, because two implementations of one
 * alphabet that have merely been read side by side are two implementations, not one.
 *
 * Three things are identical and must stay identical: the ALPHABET and the order of its symbols
 * (the order *is* the arithmetic), the CHECK SYMBOL's weights, and what CANONICALISATION strips.
 *
 * ─── WHAT IS DELIBERATELY DIFFERENT: THE LENGTH ─────────────────────────────────────────────────
 *
 * The Companion's code is 29 payload symbols (143.67 bits). This one is 20 (99.08 bits), and the
 * difference is not an oversight — the two codes guard different things against different
 * attackers.
 *
 * The Companion's code wraps a key whose wrapped blob is DESIGNED TO SIT ON A SERVER. Steal the
 * disk and you attack it offline, at whatever rate you can buy, with nobody to notice; the code
 * must therefore be unbreakable on entropy alone, which is what 143 bits buys.
 *
 * This code wraps a blob that lives in one app's private storage on one phone, alongside the
 * database it opens. An attacker holding it has already copied the phone's storage — and in that
 * situation the PIN wrap next to it is six digits, so the recovery code is not remotely the weakest
 * thing in the file. 99 bits is past the point where brute force is a consideration at all
 * (2^99 guesses is not a number that gets smaller with better hardware), and every symbol past that
 * point is another character a person copies by hand under stress and reads back later. Since
 * transcription errors scale with length while security gains scale with the logarithm, more
 * symbols here would make the code strictly worse. 20 is the shorter code that is still not
 * guessable, and this is written down so nobody "fixes" the inconsistency by lengthening it.
 *
 * ─── GROUPS OF SEVEN, NOT FIVE ──────────────────────────────────────────────────────────────────
 *
 * The Companion prints six groups of five because thirty divides by five. Twenty-one does not: it
 * would give four groups of five and a stray group of one, and a one-character group is the worst
 * possible shape — it reads as a typo, it invites being dropped when the code is copied, and
 * `groups.ts` explains at length why per-group position arithmetic goes wrong the moment a group is
 * short. 21 = 3 x 7, so three groups of seven keeps the convention (equal groups, hyphen
 * separated, count derived from the length rather than written down) with no ragged tail.
 *
 * ─── NO LOGGING, NO ECHO, NO CORRECTION ─────────────────────────────────────────────────────────
 *
 * Same three rules as the original. Nothing here writes to a log. No fault message contains any
 * part of what was typed — positions are reported, characters are not — because a fault message is
 * the thing most likely to be screenshotted into a support thread and half of what it would be
 * quoting is a live key. And the check symbol DETECTS without CORRECTING: its syndrome can be
 * solved for a plausible correction at every position at once, so "did you mean" would be a guess
 * dressed as help, and a guess that happens to produce a valid-looking code derives a DIFFERENT key
 * and surfaces as an opaque decrypt failure — exactly the outcome the check symbol exists to
 * prevent.
 */

/** A generated code, in both the form the KDF eats and the form a person copies down. */
data class RecoveryCode(
    /** 21 symbols, no separators, upper case. THIS is the KDF input — see [DataKeyWraps]. */
    val canonical: String,
    /** The same 21 symbols as `XXXXXXX-XXXXXXX-XXXXXXX`, for showing and writing down. */
    val display: String,
)

/** Every distinguishable way a typed code can fail to be a code. One value per diagnosis. */
enum class RecoveryCodeFault {
    /** Nothing was typed, or only separators were. */
    EMPTY,

    /** A 0, O, 1, I or L — characters this alphabet excludes precisely so this is unambiguous. */
    CONFUSABLE,

    /** Some other character that is not a symbol: punctuation, a letter we do not use. */
    NOT_IN_ALPHABET,
    TOO_SHORT,
    TOO_LONG,

    /** Well-formed, right length, and the check symbol disagrees — a misread or mistyped character. */
    CHECKSUM,
}

/** The result of reading a typed code: the code, or exactly why it is not one. */
sealed interface RecoveryCodeParse {
    data class Ok(val code: RecoveryCode) : RecoveryCodeParse

    /** [at] is a 1-based position among the canonical symbols, where the fault has one. */
    data class Fault(val fault: RecoveryCodeFault, val at: Int? = null) : RecoveryCodeParse
}

object RecoveryCodes {

    /**
     * The 31 symbols, in the order that defines each symbol's numeric value (index 0..30).
     *
     * The order is the only thing that must never change once a single code has been written down:
     * it is the alphabet AND the check-symbol arithmetic. Reordering it silently invalidates every
     * code any person has ever copied onto paper, and nothing in the app would report a fault —
     * their code would simply stop opening their journal.
     */
    const val ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"

    /** 31 — prime, which is the property [checkSymbol] depends on. */
    val ALPHABET_SIZE = ALPHABET.length

    /** Symbols carrying entropy. See the header for why this is 20 and the Companion's is 29. */
    const val PAYLOAD_SYMBOLS = 20

    /** Symbols spent on the check value. One. */
    const val CHECK_SYMBOLS = 1

    /** Total symbols in a canonical code. */
    const val CODE_SYMBOLS = PAYLOAD_SYMBOLS + CHECK_SYMBOLS

    /** Symbols per display group. Three groups of seven; see the header for why not five. */
    const val GROUP_SIZE = 7

    /** Derived, not written, so it tracks the code it displays. */
    const val GROUP_COUNT = CODE_SYMBOLS / GROUP_SIZE

    /** Characters that can never appear in a code, so seeing one is a definite error, not a guess. */
    private val NEVER_IN_A_CODE = setOf('0', 'O', '1', 'I', 'L')

    /** Separators a code picks up on its way through a word processor, a chat client or a PDF. */
    private val SEPARATORS = Regex("[\\s\\-\\u2010-\\u2015]+")

    /**
     * 99.08 bits. Computed rather than written, so the constant cannot drift away from the alphabet
     * and length it describes; asserted against a floor in the tests.
     */
    val ENTROPY_BITS: Double
        get() = PAYLOAD_SYMBOLS * (Math.log(ALPHABET_SIZE.toDouble()) / Math.log(2.0))

    /**
     * What to show a person for each fault.
     *
     * Sentences, not codes, because the person reading them is mid-recovery and is not having a good
     * day. None echoes the input, none implies the entries are gone, and none congratulates anybody
     * for anything. The 1-based position is carried on the parse result rather than baked into
     * these strings, so a caller can point at the character without this file having to compose
     * the sentence.
     */
    fun faultText(fault: RecoveryCodeFault): String = when (fault) {
        RecoveryCodeFault.EMPTY -> "No recovery code was entered."
        RecoveryCodeFault.CONFUSABLE ->
            "Recovery codes never contain the characters 0, O, 1, I or L. Check that character again."
        RecoveryCodeFault.NOT_IN_ALPHABET -> "That character is not one a recovery code uses."
        RecoveryCodeFault.TOO_SHORT ->
            "That is fewer characters than a recovery code has. Some may be missing."
        RecoveryCodeFault.TOO_LONG -> "That is more characters than a recovery code has."
        RecoveryCodeFault.CHECKSUM ->
            "One character does not match the rest of the code. It is worth reading it back once more."
    }

    /**
     * Strip everything a person might reasonably add, and upper-case the rest.
     *
     * Spaces, tabs, newlines and hyphens go because we PUT the hyphens there — refusing to read back
     * the format we printed would be absurd. The Unicode dashes (U+2010..U+2015) are here because a
     * code that has been through a word processor, a chat client or a PDF comes back with en and em
     * dashes in place of the hyphens, and that is a formatting artefact rather than a mistake by the
     * person.
     *
     * Nothing else is normalised. In particular O is NOT folded to 0 and I/L are NOT folded to 1 —
     * that is the Crockford behaviour this alphabet deliberately does not need, and doing it anyway
     * would turn a character we can diagnose exactly into a silent substitution.
     */
    fun normalizeInput(typed: String): String = SEPARATORS.replace(typed, "").uppercase()

    /**
     * The check symbol's numeric value: sum of (position x symbol value) mod 31.
     *
     * WHAT THIS PROVABLY CATCHES. Positions are weighted 1..20, all distinct and none of them zero
     * mod 31. Because 31 is PRIME the integers mod 31 form a field, so a product of two non-zero
     * values is never zero. Two consequences, and they are the whole reason the alphabet is 31
     * symbols long rather than a bit-aligned 32:
     *
     *  - ANY single mistyped or misread symbol is caught, with certainty. Changing the symbol at
     *    position i shifts the sum by w_i x delta, with w_i non-zero and delta non-zero, so the sum
     *    always moves. Not "almost always" — always. This is the case the feature is for: one
     *    character read wrong off a piece of paper.
     *  - ANY transposition of two different symbols is caught, with certainty. Swapping positions i
     *    and j shifts the sum by (w_i - w_j)(d_j - d_i); the weights differ by at most 19, so their
     *    difference is never zero mod 31, and the symbols differ by assumption.
     *
     * WHAT ONE CHECK SYMBOL DOES NOT BUY, SAID PLAINLY. Against input mangled in several places at
     * once — a whole group dropped, two characters swapped for two others — one symbol of check
     * gives a 1-in-31 chance of passing anyway, and the failure then surfaces one layer down as a
     * decrypt that does not work. That residual is accepted: a second check symbol would buy
     * 1-in-961 against the multi-error case while making every person copy another character, and
     * the single-error case — the realistic one, already at certainty — would not improve at all.
     */
    private fun checkValue(payload: String): Int {
        var sum = 0
        for (i in payload.indices) {
            val value = ALPHABET.indexOf(payload[i])
            // Callers reach here only through parse() (which validated every character first) or
            // through generate() (which drew them from the alphabet). A symbol that is in neither
            // would index at -1 and quietly produce a plausible-looking wrong check value, so it
            // stops here instead: a check symbol computed over something that is not a payload is
            // worse than no check symbol at all.
            require(value >= 0) { "a check symbol was computed over something that is not a payload" }
            sum = (sum + (i + 1) * value) % ALPHABET_SIZE
        }
        return sum
    }

    /** The check symbol for a payload. */
    fun checkSymbol(payload: String): Char = ALPHABET[checkValue(payload)]

    /** Canonical symbols to `XXXXXXX-XXXXXXX-XXXXXXX`, which is the form a person sees. */
    fun format(canonical: String): String =
        canonical.chunked(GROUP_SIZE).joinToString("-")

    /**
     * Read a typed code, or say exactly why it is not one.
     *
     * ORDER OF DIAGNOSIS, AND WHY. Characters are checked before length, because a person who pasted
     * a sentence is better served by "that character is not one a recovery code uses" than by "that
     * is more characters than a recovery code has" — the first says what they pasted, the second
     * says how much of it. Length is checked before the check symbol because a check symbol computed
     * over the wrong number of symbols is meaningless.
     */
    fun parse(typed: String): RecoveryCodeParse {
        val canonical = normalizeInput(typed)
        if (canonical.isEmpty()) return RecoveryCodeParse.Fault(RecoveryCodeFault.EMPTY)
        for (i in canonical.indices) {
            val ch = canonical[i]
            if (ch in NEVER_IN_A_CODE) {
                return RecoveryCodeParse.Fault(RecoveryCodeFault.CONFUSABLE, i + 1)
            }
            if (!ALPHABET.contains(ch)) {
                return RecoveryCodeParse.Fault(RecoveryCodeFault.NOT_IN_ALPHABET, i + 1)
            }
        }
        if (canonical.length < CODE_SYMBOLS) return RecoveryCodeParse.Fault(RecoveryCodeFault.TOO_SHORT)
        if (canonical.length > CODE_SYMBOLS) return RecoveryCodeParse.Fault(RecoveryCodeFault.TOO_LONG)
        val payload = canonical.substring(0, PAYLOAD_SYMBOLS)
        if (canonical[PAYLOAD_SYMBOLS] != checkSymbol(payload)) {
            return RecoveryCodeParse.Fault(RecoveryCodeFault.CHECKSUM)
        }
        return RecoveryCodeParse.Ok(RecoveryCode(canonical, format(canonical)))
    }

    /**
     * A fresh code, drawn uniformly from the alphabet.
     *
     * WHY REJECTION SAMPLING RATHER THAN A MODULO. 256 is not a multiple of 31 (it is 8 x 31 + 8),
     * so `randomByte % 31` would hand out the first eight symbols nine times in 256 draws and the
     * rest eight — a small bias, but a bias in the ONE place where uniformity is the entire security
     * argument, and free to remove. Bytes at or above 248 are discarded and redrawn; every symbol
     * then has probability exactly 8/248.
     *
     * [random] is a parameter so a test can drive the rejection path with a fixed byte stream
     * instead of hoping a 248 turns up. Production callers take the default.
     */
    fun generate(random: SecureRandom = SecureRandom()): RecoveryCode {
        val limit = ALPHABET_SIZE * (256 / ALPHABET_SIZE) // 248
        val symbols = StringBuilder(CODE_SYMBOLS)
        val draw = ByteArray(PAYLOAD_SYMBOLS)
        while (symbols.length < PAYLOAD_SYMBOLS) {
            random.nextBytes(draw)
            for (b in draw) {
                if (symbols.length >= PAYLOAD_SYMBOLS) break
                val value = b.toInt() and 0xFF
                if (value < limit) symbols.append(ALPHABET[value % ALPHABET_SIZE])
            }
        }
        draw.fill(0)
        val payload = symbols.toString()
        val canonical = payload + checkSymbol(payload)
        return RecoveryCode(canonical, format(canonical))
    }
}
