package com.daymark.app.security

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.security.SecureRandom

/**
 * The Kotlin recovery code is the same code the Companion prints, and these are the vectors that
 * say so.
 *
 * ## Why fixed vectors and not "read both files carefully"
 *
 * `companion/web/src/lib/recovery/recoveryCode.ts` and `RecoveryCode.kt` are two implementations of
 * one alphabet and one weighted checksum. Two implementations that have merely been compared by eye
 * are two implementations: a transposed pair of symbols in the alphabet, an off-by-one in the
 * position weights, an `uppercase()` applied before rather than after separators are stripped — none
 * of those is visible in a diff between two languages, and every one of them produces codes that
 * look exactly right and open nothing.
 *
 * So the vectors below were GENERATED by running the TypeScript module under vitest and pasted here
 * verbatim. The generator is not committed — it was twenty lines importing `checkSymbol`,
 * `normalizeRecoveryInput` and `formatRecoveryCode` and printing their output for a
 * deterministically-seeded set of payloads. If these ever need regenerating, that is the recipe:
 * the values here must come from the TypeScript, never from this file's own arithmetic, or the
 * parity claim is circular and proves nothing.
 *
 * ## What parity does and does not mean here
 *
 * The two codes are different LENGTHS on purpose (20 payload symbols here, 29 there; the header of
 * `RecoveryCode.kt` says why), so no vector below is a whole Companion code. What is pinned is
 * everything that is length-independent and would silently diverge: the alphabet and its ORDER, the
 * check symbol's arithmetic over a payload of any length, and exactly what canonicalisation strips
 * and folds.
 */
class RecoveryCodeTest {

    // ─── Vectors generated by the TypeScript module ────────────────────────────────────────────

    /** `RECOVERY_ALPHABET` as the TypeScript prints it. The ORDER is the arithmetic. */
    private val tsAlphabet = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"

    /**
     * `payload -> checkSymbol(payload)` over 20-symbol payloads, from the TypeScript. The last four
     * are edge payloads: every symbol the first, every symbol the last, and the alphabet walked in
     * order from each end.
     */
    private val checkVectors: List<Pair<String, Char>> = listOf(
        "EAW2MQR73G9V7ZSURHVY" to '8',
        "54ZFXUHAGAHHJH8VVFDZ" to '5',
        "MYYC9GXXPHS9VMFFUSQ8" to 'B',
        "69H2AV5T3YY4ABKEU58Z" to 'A',
        "YXEQH9E7GFP4ZEXQTVTX" to 'Y',
        "FAK72UUFJZ7WEH2N6V39" to 'P',
        "NMAXM2MM22YEBKWB3B8H" to '2',
        "JVJBKX7KUH6MDJB74XJH" to 'Q',
        "QSMJ27CUUY96DA4QUWW3" to 'X',
        "NC6H4YD44QX39F7NXRVD" to 'E',
        "4H9KBDUF9ZJQPV4JC23B" to 'A',
        "TQ2TZFJ5BY5YT3FHY5UM" to 'D',
        "RSV92PQN3BS6WW9ZVZVG" to '4',
        "MWEX98YAH2E8WS3ETNCZ" to '2',
        "CXUFJY8UNDSA7RNYY2TU" to 'H',
        "NGX47FN58SZ9NDFPFCN8" to 'E',
        "XT97EUCZRYXKNEWTR9MA" to 'Z',
        "CCAAMPRUW6BZYEQXRUSE" to 'J',
        "M24N6M2WHH8WFSHB76PH" to 'V',
        "J7ATVAXBMGQTWKZMHF5K" to 'Z',
        "7MA4NRJWKT6XRXQ2FG38" to 'Z',
        "EUP69G8SE252ASU374YY" to 'W',
        "AWXU6NT2A2NNP2UTF28U" to 'X',
        "6767YAFZ9WYPZ8QJ682V" to 'C',
        "22222222222222222222" to '2',
        "ZZZZZZZZZZZZZZZZZZZZ" to '9',
        "23456789ABCDEFGHJKMN" to 'U',
        "DEFGHJKMNPQRSTUVWXYZ" to 'C',
    )

    /** `normalizeRecoveryInput(raw) -> canonical`, from the TypeScript. */
    private val normaliseVectors: List<Pair<String, String>> = listOf(
        "abcde-fghjk" to "ABCDEFGHJK",
        " 2345 6789 " to "23456789",
        "23456—7899" to "234567899", // em dash
        "23456‐7899" to "234567899", // hyphen U+2010
        "23456―7899" to "234567899", // horizontal bar U+2015
        "23456\t\n7899" to "234567899",
        "ab-cd--ef---gh" to "ABCDEFGH",
        "zZ9-qQ8" to "ZZ9QQ8",
        // The confusables are UPPER-CASED and NOT folded. This is the vector that would catch
        // someone "helpfully" adding Crockford's O->0 and I/L->1 mapping to one side only.
        "o0l1i" to "O0L1I",
        "" to "",
        "-----" to "",
        "  \t\n " to "",
    )

    // ─── Parity ────────────────────────────────────────────────────────────────────────────────

    @Test
    fun `the alphabet is the Companion's alphabet, in the Companion's order`() {
        assertEquals(
            "the alphabet diverged from companion/web/src/lib/recovery/recoveryCode.ts. Its ORDER " +
                "is the check-symbol arithmetic: reordering it invalidates every code any person " +
                "has ever written down, silently, with no fault reported anywhere.",
            tsAlphabet,
            RecoveryCodes.ALPHABET,
        )
        assertEquals(31, RecoveryCodes.ALPHABET_SIZE)
        // 31 must be prime or the check symbol stops catching every single-symbol error.
        assertTrue("31 is not prime", (2 until 31).none { 31 % it == 0 })
        // The five characters the alphabet gives up, so that seeing one is a diagnosis.
        for (ch in listOf('0', 'O', '1', 'I', 'L')) {
            assertFalse("$ch is in the alphabet", RecoveryCodes.ALPHABET.contains(ch))
        }
    }

    @Test
    fun `every check symbol matches the TypeScript`() {
        // Guards the loop below: an empty vector list would make it pass having checked nothing.
        assertEquals(28, checkVectors.size)
        for ((payload, expected) in checkVectors) {
            assertEquals(RecoveryCodes.PAYLOAD_SYMBOLS, payload.length)
            assertEquals(
                "check symbol for $payload diverged from the TypeScript",
                expected,
                RecoveryCodes.checkSymbol(payload),
            )
        }
    }

    @Test
    fun `canonicalisation strips and folds exactly what the TypeScript does`() {
        assertEquals(12, normaliseVectors.size)
        for ((raw, expected) in normaliseVectors) {
            assertEquals(
                "normalizeInput diverged on ${raw.map { it.code }}",
                expected,
                RecoveryCodes.normalizeInput(raw),
            )
        }
    }

    // ─── Shape ─────────────────────────────────────────────────────────────────────────────────

    @Test
    fun `the code is twenty payload symbols, one check symbol, three groups of seven`() {
        assertEquals(20, RecoveryCodes.PAYLOAD_SYMBOLS)
        assertEquals(1, RecoveryCodes.CHECK_SYMBOLS)
        assertEquals(21, RecoveryCodes.CODE_SYMBOLS)
        assertEquals(7, RecoveryCodes.GROUP_SIZE)
        // Three groups of seven, with nothing left over. A ragged final group of one character is
        // the shape this length was chosen to avoid — see the header of RecoveryCode.kt.
        assertEquals(3, RecoveryCodes.GROUP_COUNT)
        assertEquals(
            RecoveryCodes.CODE_SYMBOLS,
            RecoveryCodes.GROUP_COUNT * RecoveryCodes.GROUP_SIZE,
        )
    }

    @Test
    fun `the code is past the point where guessing it is a consideration`() {
        // 20 x log2(31) = 99.08. The floor is stated as a number rather than a feeling: below ~96
        // bits somebody could start writing a budget for the search, and this key is not
        // re-issuable once a person has written it on paper.
        assertTrue("entropy is ${RecoveryCodes.ENTROPY_BITS} bits", RecoveryCodes.ENTROPY_BITS > 96.0)
        assertTrue(RecoveryCodes.ENTROPY_BITS < 100.0)
    }

    @Test
    fun `display groups are hyphen separated and reversible`() {
        val canonical = "23456789ABCDEFGHJKMNU"
        assertEquals("2345678-9ABCDEF-GHJKMNU", RecoveryCodes.format(canonical))
        assertEquals(canonical, RecoveryCodes.normalizeInput(RecoveryCodes.format(canonical)))
    }

    // ─── The error check, which is the whole reason for 31 symbols ─────────────────────────────

    /**
     * The property the alphabet's primality buys, exercised rather than asserted in prose.
     *
     * Every payload in the vectors, every position, every other symbol: the code must be refused.
     * This is the realistic error — one character read wrong off a piece of paper — and the claim
     * is that it is caught with CERTAINTY, not usually.
     */
    @Test
    fun `every single-character misreading is caught`() {
        var mutations = 0
        for ((payload, check) in checkVectors) {
            val canonical = payload + check
            for (i in canonical.indices) {
                for (replacement in RecoveryCodes.ALPHABET) {
                    if (replacement == canonical[i]) continue
                    val mutated = canonical.substring(0, i) + replacement + canonical.substring(i + 1)
                    mutations++
                    assertTrue(
                        "a one-character change at position ${i + 1} was accepted as a code",
                        RecoveryCodes.parse(mutated) is RecoveryCodeParse.Fault,
                    )
                }
            }
        }
        // 28 codes x 21 positions x 30 replacements.
        assertEquals(28 * 21 * 30, mutations)
    }

    /**
     * The positive control for the test above.
     *
     * A loop that refuses everything would pass it — including a `parse` that had been broken to
     * return a fault unconditionally, which is the single most likely way for that assertion to go
     * green while proving nothing. So the same loop is run with the "mutation" being a replacement
     * of each character BY ITSELF, and every one of those must be ACCEPTED.
     */
    @Test
    fun `the mutation loop is running against a parser that accepts correct codes`() {
        var identities = 0
        for ((payload, check) in checkVectors) {
            val canonical = payload + check
            for (i in canonical.indices) {
                val same = canonical.substring(0, i) + canonical[i] + canonical.substring(i + 1)
                identities++
                val parsed = RecoveryCodes.parse(same)
                assertTrue(
                    "an unmutated code was refused — the mutation test above proves nothing",
                    parsed is RecoveryCodeParse.Ok,
                )
                assertEquals(canonical, (parsed as RecoveryCodeParse.Ok).code.canonical)
            }
        }
        assertEquals(28 * 21, identities)
    }

    @Test
    fun `every transposition of two different symbols is caught`() {
        var swaps = 0
        for ((payload, check) in checkVectors.take(6)) {
            val canonical = payload + check
            for (i in canonical.indices) {
                for (j in i + 1 until canonical.length) {
                    if (canonical[i] == canonical[j]) continue
                    val chars = canonical.toCharArray()
                    val tmp = chars[i]; chars[i] = chars[j]; chars[j] = tmp
                    swaps++
                    assertTrue(
                        "swapping positions ${i + 1} and ${j + 1} was accepted as a code",
                        RecoveryCodes.parse(String(chars)) is RecoveryCodeParse.Fault,
                    )
                }
            }
        }
        assertTrue("no transpositions were exercised", swaps > 1000)
    }

    // ─── Diagnosis ─────────────────────────────────────────────────────────────────────────────

    @Test
    fun `each way of not being a code is named separately`() {
        val good = "23456789ABCDEFGHJKMNU"

        assertEquals(RecoveryCodeFault.EMPTY, faultOf(""))
        assertEquals(RecoveryCodeFault.EMPTY, faultOf("---- "))

        // A confusable is positioned exactly, which is the entire reason 0/O/1/I/L were given up.
        val confusable = RecoveryCodes.parse("23456O89ABCDEFGHJKMNU") as RecoveryCodeParse.Fault
        assertEquals(RecoveryCodeFault.CONFUSABLE, confusable.fault)
        assertEquals(6, confusable.at!!)

        val notInAlphabet = RecoveryCodes.parse("23456#89ABCDEFGHJKMNU") as RecoveryCodeParse.Fault
        assertEquals(RecoveryCodeFault.NOT_IN_ALPHABET, notInAlphabet.fault)
        assertEquals(6, notInAlphabet.at!!)

        assertEquals(RecoveryCodeFault.TOO_SHORT, faultOf(good.dropLast(1)))
        assertEquals(RecoveryCodeFault.TOO_LONG, faultOf(good + "2"))

        // Characters before length: a pasted sentence is diagnosed as its character, not its size.
        assertEquals(RecoveryCodeFault.NOT_IN_ALPHABET, faultOf("23456789ABCDEFGHJKMNU23456789#"))

        // Right shape, wrong check symbol.
        assertEquals(RecoveryCodeFault.CHECKSUM, faultOf(good.dropLast(1) + "V"))
    }

    @Test
    fun `no fault message echoes any part of what was typed`() {
        // A fault message is the thing most likely to be screenshotted into a support thread, and
        // half of what it would be quoting is a live key.
        val typed = "QSMJ27CUUY96DA4QUWW3X"
        for (fault in RecoveryCodeFault.entries) {
            val text = RecoveryCodes.faultText(fault)
            for (window in typed.windowed(4)) {
                assertFalse(
                    "the message for $fault contains \"$window\" from the typed code",
                    text.contains(window, ignoreCase = true),
                )
            }
        }
    }

    /** The positive control: the echo detector must be able to see an echo. */
    @Test
    fun `the echo detector can see a planted echo`() {
        val typed = "QSMJ27CUUY96DA4QUWW3X"
        val planted = "The code QSMJ27C was not recognised."
        assertTrue(
            "the echo detector is blind — its clean report on the real messages proves nothing",
            typed.windowed(4).any { planted.contains(it, ignoreCase = true) },
        )
    }

    @Test
    fun `fault text says nothing about the entries being gone and congratulates nobody`() {
        for (fault in RecoveryCodeFault.entries) {
            val text = RecoveryCodes.faultText(fault).lowercase()
            for (word in listOf("lost", "gone", "deleted", "destroyed", "success", "correct!", "well done")) {
                assertFalse("the message for $fault says \"$word\"", text.contains(word))
            }
        }
    }

    // ─── Generation ────────────────────────────────────────────────────────────────────────────

    /** A SecureRandom that hands out a fixed byte stream, so the rejection path can be driven. */
    private class FixedBytes(private val stream: List<Int>) : SecureRandom() {
        private var at = 0
        override fun nextBytes(bytes: ByteArray) {
            for (i in bytes.indices) bytes[i] = stream[at++ % stream.size].toByte()
        }
    }

    @Test
    fun `a generated code parses, and parses to itself`() {
        val random = SecureRandom()
        repeat(200) {
            val code = RecoveryCodes.generate(random)
            assertEquals(21, code.canonical.length)
            assertEquals("2345678-9ABCDEF-GHJKMNU".length, code.display.length)
            val parsed = RecoveryCodes.parse(code.display)
            assertTrue("a freshly generated code did not parse: ${code.display.length} symbols", parsed is RecoveryCodeParse.Ok)
            assertEquals(code.canonical, (parsed as RecoveryCodeParse.Ok).code.canonical)
        }
    }

    /**
     * Bytes at or above 248 are discarded rather than folded, because `byte % 31` would hand out the
     * first eight symbols nine times in 256 draws and the rest eight — a bias in the one place where
     * uniformity is the whole security argument.
     *
     * The stream here is twenty bytes that must ALL be rejected, then the values 0..19. If rejection
     * were dropped, the first twenty bytes would produce symbols and the payload would be wrong.
     * The expected payload is the alphabet's first twenty symbols, whose check symbol U came from
     * the TypeScript vectors above — so this also ties the generator to the shared arithmetic.
     */
    @Test
    fun `bytes above the rejection limit are discarded, not folded`() {
        val rejected = (248..255).toList()
        val stream = List(20) { rejected[it % rejected.size] } + (0..19).toList()
        val code = RecoveryCodes.generate(FixedBytes(stream))
        assertEquals("23456789ABCDEFGHJKMNU", code.canonical)
        assertEquals("2345678-9ABCDEF-GHJKMNU", code.display)
    }

    @Test
    fun `two generated codes differ`() {
        // Not a uniformity proof; a smoke test that the generator is not returning a constant, which
        // is what a mis-wired SecureRandom looks like from the outside.
        val random = SecureRandom()
        assertNotEquals(RecoveryCodes.generate(random).canonical, RecoveryCodes.generate(random).canonical)
    }

    @Test
    fun `every symbol of the alphabet can be drawn`() {
        // A modulo or slice error typically shows up as a symbol that never appears.
        val random = SecureRandom()
        val seen = mutableSetOf<Char>()
        repeat(2000) { seen.addAll(RecoveryCodes.generate(random).canonical.toList()) }
        assertEquals(
            "some symbols are never drawn: ${RecoveryCodes.ALPHABET.filterNot { it in seen }}",
            31,
            seen.size,
        )
    }

    private fun faultOf(typed: String): RecoveryCodeFault =
        (RecoveryCodes.parse(typed) as RecoveryCodeParse.Fault).fault
}
