import { describe, it, expect } from 'vitest'
import {
  ADMIN_ENDPOINTS,
  AUDIENCE_LABEL,
  BUSY_WORD,
  DETAIL_LIMIT,
  PANEL_FOOTER,
  PANEL_LEDE,
  PROBE_ORDER,
  PROBE_PATH,
  STANDING_STRINGS,
  SYNC_NOT_PROBED,
  VERDICT_WORD,
  authoredStrings,
  classifyOrigin,
  describeLastChecked,
  interpretServerState,
  readProbeLine,
  summariseBody,
  type ProbeResponse,
  type ProbeSet,
  type ServerStateId,
  type ServerStateReading,
} from './serverState'
import { describeLastChecked as adminDescribeLastChecked } from '../admin/health'

/*
 * ═══════════════════════════════════════════════════════════════════════════════════════════════
 * WHAT THIS SUITE IS FOR
 * ═══════════════════════════════════════════════════════════════════════════════════════════════
 *
 * The panel this covers is served to ANYONE who can reach the server, unauthenticated. Its whole
 * design constraint is a claim about what it does NOT say: it may restate what the server already
 * tells an anonymous caller and nothing beyond that. Every other property — the states, the
 * ordering, the truncation — exists to keep that claim true.
 *
 * A test for an absence is the easiest test in the world to write vacuously. `expect(hits)
 * .toEqual([])` over a corpus that turned out to be empty, or against a regex that never matched
 * anything, passes forever and removes the appetite to write a real one. So:
 *
 *   · every detector below is first shown FIRING on a planted example, in the same test;
 *   · the corpus is asserted non-empty and asserted to contain sentences the module really ships,
 *     before it is filtered;
 *   · the corpus is generated by running the module over an exhaustive matrix of inputs rather
 *     than by listing its constants, so a sentence reachable only from an odd combination of
 *     responses is still covered.
 *
 * And the containment test runs the other way round: a response whose error string and body are
 * stuffed with every withheld subject at once must leave those words in `detail` and NOWHERE else.
 * That proves the scan has teeth — if authored copy and machine bytes were ever merged into one
 * field, the scan would light up.
 */

/* ═══════════════════════════════════════════════════════════════════════════════════════════════
   Fixtures: the exact bodies companion/server sends.
   ═══════════════════════════════════════════════════════════════════════════════════════════════ */

const OK_TRUE: ProbeResponse = { kind: 'response', status: 200, body: '{"ok":true}' }
const OK_FALSE_503: ProbeResponse = { kind: 'response', status: 503, body: '{"ok":false}' }
const CONFIG_ON: ProbeResponse = { kind: 'response', status: 200, body: '{"smtpEnabled":true}' }
const CONFIG_OFF: ProbeResponse = { kind: 'response', status: 200, body: '{"smtpEnabled":false}' }
const GONE: ProbeResponse = { kind: 'transport', error: 'TypeError: Failed to fetch' }
const PROXY_PAGE: ProbeResponse = {
  kind: 'response',
  status: 502,
  body: '<html><head><title>502 Bad Gateway</title></head><body>upstream</body></html>',
}

const healthy: ProbeSet = { liveness: OK_TRUE, writability: OK_TRUE, capability: CONFIG_OFF }
const notReady: ProbeSet = { liveness: OK_TRUE, writability: OK_FALSE_503, capability: CONFIG_OFF }
const allGone: ProbeSet = { liveness: GONE, writability: GONE, capability: GONE }
const someGone: ProbeSet = { liveness: OK_TRUE, writability: GONE, capability: CONFIG_OFF }
const strange: ProbeSet = { liveness: OK_TRUE, writability: OK_TRUE, capability: PROXY_PAGE }

const read = (protocol: string, probes: ProbeSet | null): ServerStateReading =>
  interpretServerState({ protocol, probes })

/* ═══════════════════════════════════════════════════════════════════════════════════════════════
   The URLs, and the reuse boundary with the admin console.
   ═══════════════════════════════════════════════════════════════════════════════════════════════ */

describe('the endpoints this panel reads', () => {
  it('are the three the server actually registers, at the paths the admin console uses', () => {
    // Parity rather than duplication. Both consoles read the same three unauthenticated endpoints;
    // if someone adds a fourth to the admin catalogue, or moves one, this fails instead of the two
    // screens quietly diverging onto different URLs.
    expect(ADMIN_ENDPOINTS.length).toBe(3)
    for (const ep of ADMIN_ENDPOINTS) {
      expect(PROBE_PATH[ep.id], `${ep.id} drifted`).toBe(ep.path)
      expect(ep.authenticated, `${ep.path} is no longer credential-free`).toBe(false)
    }
    expect([...PROBE_ORDER].sort()).toEqual(ADMIN_ENDPOINTS.map((e) => e.id).sort())
    // The literal paths, so a rename in both places at once still has to be deliberate.
    expect(PROBE_PATH.liveness).toBe('/healthz')
    expect(PROBE_PATH.writability).toBe('/readyz')
    expect(PROBE_PATH.capability).toBe('/v1/config')
  })

  it('reuses the staleness vocabulary instead of copying it', () => {
    // Identity, not equivalence: a second implementation would drift, and "checked 3 minutes ago"
    // appearing in two spellings across two consoles is exactly the kind of drift nobody notices.
    expect(describeLastChecked).toBe(adminDescribeLastChecked)
    expect(describeLastChecked(null, 1_000)).toBe('not checked yet')
    expect(describeLastChecked(0, 120_000)).toBe('checked 2 minutes ago')
  })
})

/* ═══════════════════════════════════════════════════════════════════════════════════════════════
   Where the page came from.
   ═══════════════════════════════════════════════════════════════════════════════════════════════ */

describe('a page opened from a file is not a broken server', () => {
  it('classifies only http and https as served', () => {
    expect(classifyOrigin('http:')).toBe('served')
    expect(classifyOrigin('https:')).toBe('served')
    expect(classifyOrigin('HTTPS:')).toBe('served')
    // The whole point: `file:` must not read as "served", or the panel invents a server outage.
    expect(classifyOrigin('file:')).toBe('local-file')
    expect(classifyOrigin('blob:')).toBe('local-file')
    expect(classifyOrigin('data:')).toBe('local-file')
    expect(classifyOrigin('about:')).toBe('local-file')
    expect(classifyOrigin('')).toBe('local-file')
  })

  it('reports "no server involved" and asks nothing, even if responses are handed in', () => {
    // Belt and braces. The component is supposed not to fetch from a file: page, but if it ever
    // did, the reading must still not present those results as being about a server.
    const r = read('file:', allGone)
    expect(r.id).toBe('page-not-served')
    expect(r.probes).toEqual([])
    expect(r.mail).toBeNull()
    expect(r.syncNote).toBeNull()
    expect(r.tone).toBe('neutral')
    // And it must not be alarming: this is the ordinary Phase-0 offline case.
    expect(r.observed).toContain('opened from a file on this device')
    expect(r.means).toContain('never')
  })

  it('says so before it says "not checked", because the reasons differ', () => {
    expect(read('file:', null).id).toBe('page-not-served')
    expect(read('https:', null).id).toBe('not-checked')
    expect(read('https:', null).probes).toEqual([])
  })
})

/* ═══════════════════════════════════════════════════════════════════════════════════════════════
   Reading one probe.
   ═══════════════════════════════════════════════════════════════════════════════════════════════ */

describe('each probe is read against the shape the server really sends', () => {
  it('recognises the documented answers', () => {
    expect(readProbeLine('liveness', OK_TRUE).verdict).toBe('answered')
    expect(readProbeLine('writability', OK_TRUE).verdict).toBe('answered')
    expect(readProbeLine('writability', OK_FALSE_503).verdict).toBe('refused')
    expect(readProbeLine('capability', CONFIG_ON).verdict).toBe('answered')
    expect(readProbeLine('capability', CONFIG_ON).smtpEnabled).toBe(true)
    expect(readProbeLine('capability', CONFIG_OFF).smtpEnabled).toBe(false)
  })

  it('does not read a 503 as "refused" unless it carries the documented body', () => {
    // The presence half first: the detector really does fire on the real answer.
    expect(readProbeLine('writability', OK_FALSE_503).verdict).toBe('refused')
    // A 503 from something in front of the server is not the server refusing readiness. Reading it
    // as one would send an operator to look at a directory that is fine.
    const gatewayish: ProbeResponse = { kind: 'response', status: 503, body: 'Service Unavailable' }
    expect(readProbeLine('writability', gatewayish).verdict).toBe('undocumented')
    // …and only readiness has a documented 503 at all.
    expect(readProbeLine('liveness', OK_FALSE_503).verdict).toBe('undocumented')
  })

  it('states that the 503 carries no reason, because the server states no reason', () => {
    // Readiness.kt keeps Result.reason for the log and responds with the literal {"ok":false}.
    // If this sentence ever softens into a guess about which failure it is, the panel has started
    // telling an anonymous caller something the server withheld from them.
    const l = readProbeLine('writability', OK_FALSE_503)
    expect(l.observed).toContain('carries no reason')
    expect(l.detail).toBeNull()
  })

  it('never invents a reading from an unparseable body', () => {
    for (const body of ['', 'null', '[]', '{"ok":"true"}', '{"ok":1}', 'not json at all']) {
      expect(readProbeLine('liveness', { kind: 'response', status: 200, body }).verdict).toBe(
        'undocumented',
      )
    }
    for (const body of ['{}', '{"smtpEnabled":"yes"}', '{"smtp":true}']) {
      expect(readProbeLine('capability', { kind: 'response', status: 200, body }).verdict).toBe(
        'undocumented',
      )
      expect(readProbeLine('capability', { kind: 'response', status: 200, body }).smtpEnabled).toBe(
        undefined,
      )
    }
  })

  it('is total: every id and every response shape yields a line with both halves', () => {
    const shapes: ProbeResponse[] = [
      OK_TRUE,
      OK_FALSE_503,
      CONFIG_ON,
      PROXY_PAGE,
      GONE,
      { kind: 'response', status: 418, body: 'teapot' },
    ]
    for (const id of PROBE_ORDER) {
      for (const res of shapes) {
        const l = readProbeLine(id, res)
        expect(l.id).toBe(id)
        expect(l.endpoint).toBe(`GET ${PROBE_PATH[id]}`)
        expect(l.label.length).toBeGreaterThan(5)
        // "Establishes" and "does not establish" are never separated: a reader who gets one
        // without the other has learned the wrong thing.
        expect(l.observed.length).toBeGreaterThan(20)
        expect(l.silentOn.length).toBeGreaterThan(40)
        expect(VERDICT_WORD[l.verdict]).toBeTruthy()
      }
    }
  })

  it('quotes unrecognised bytes only, and caps how much', () => {
    const long = 'x'.repeat(5_000)
    const l = readProbeLine('liveness', { kind: 'response', status: 200, body: long })
    expect(l.detail).not.toBeNull()
    expect(l.detail!.length).toBeLessThan(DETAIL_LIMIT + 40)
    expect(l.detail!).toContain('…')
    // Documented answers carry nothing machine-supplied at all.
    expect(readProbeLine('liveness', OK_TRUE).detail).toBeNull()
    expect(readProbeLine('capability', CONFIG_ON).detail).toBeNull()
  })

  it('summariseBody collapses, caps and never returns an empty string', () => {
    expect(summariseBody('  a\n\n  b  ')).toBe('a b')
    expect(summariseBody('')).toBe('(empty body)')
    expect(summariseBody('   ')).toBe('(empty body)')
    expect(summariseBody('abcdef', 3)).toBe('abc…')
    expect(summariseBody('abc', 3)).toBe('abc')
  })
})

/* ═══════════════════════════════════════════════════════════════════════════════════════════════
   The combined state.
   ═══════════════════════════════════════════════════════════════════════════════════════════════ */

describe('the states, and the order they are decided in', () => {
  it('reaches every one of them', () => {
    // Non-vacuity for the corpus scan far below: if a state were unreachable, its copy would never
    // be generated and would never be scanned.
    const seen: Record<ServerStateId, boolean> = {
      'page-not-served': false,
      'not-checked': false,
      'no-answer': false,
      'partial-answer': false,
      'not-ready': false,
      'undocumented-answer': false,
      answering: false,
    }
    seen[read('file:', null).id] = true
    seen[read('https:', null).id] = true
    seen[read('https:', allGone).id] = true
    seen[read('https:', someGone).id] = true
    seen[read('https:', notReady).id] = true
    seen[read('https:', strange).id] = true
    seen[read('https:', healthy).id] = true
    expect(Object.entries(seen).filter(([, hit]) => !hit).map(([id]) => id)).toEqual([])
  })

  it('separates "none of it answered" from "some of it answered"', () => {
    expect(read('https:', allGone).id).toBe('no-answer')
    expect(read('https:', someGone).id).toBe('partial-answer')
    // One answer is enough to make it partial rather than total silence.
    expect(read('https:', { liveness: GONE, writability: GONE, capability: CONFIG_ON }).id).toBe(
      'partial-answer',
    )
  })

  it('does not blame the server for a request that did not complete', () => {
    const r = read('https:', allGone)
    expect(r.observed).toContain('none of them completed')
    // The load-bearing hedge. "The server is down" is a claim this page cannot make: it saw no
    // reply, which is compatible with the process being fine and something else eating the request.
    expect(r.means).toContain('It does not say the server stopped')
  })

  it('puts readiness-refused above an unrecognised answer, and says why in the rows', () => {
    // A 503 carrying exactly {"ok":false} is a shape only this build sends, so receiving it is
    // strong evidence the app itself answered — and it is the most actionable thing here. An odd
    // answer elsewhere must not bury it, but must still be visible on its own row.
    const both: ProbeSet = { liveness: OK_TRUE, writability: OK_FALSE_503, capability: PROXY_PAGE }
    const r = read('https:', both)
    expect(r.id).toBe('not-ready')
    expect(r.probes.find((p) => p.id === 'capability')!.verdict).toBe('undocumented')
  })

  it('lets a missing answer outrank a refusal, because a partial read cannot be trusted', () => {
    const r = read('https:', { liveness: GONE, writability: OK_FALSE_503, capability: CONFIG_OFF })
    expect(r.id).toBe('partial-answer')
  })

  it('carries the evidence rows on every state that asked anything', () => {
    for (const probes of [healthy, notReady, allGone, someGone, strange]) {
      const r = read('https:', probes)
      expect(r.probes.map((p) => p.id)).toEqual([...PROBE_ORDER])
      expect(r.syncNote).toBe(SYNC_NOT_PROBED)
    }
  })
})

describe('the last state is a statement of fact and not a reassurance', () => {
  it('is called "Answering" and spends its words on what it does not cover', () => {
    const r = read('https:', healthy)
    expect(r.id).toBe('answering')
    expect(r.word).toBe('Answering')
    expect(r.tone).toBe('neutral')
    // The sentence the whole state exists to make.
    expect(r.means).toContain('Nothing on this screen contradicts a working setup')
    expect(r.means).toContain('that is the whole of what it means')
    // Deflation outweighs the claim: more of this paragraph is about limits than about the answers.
    expect(r.means.length).toBeGreaterThan(r.observed.length)
  })

  it('has no tone in the system that means "fine"', () => {
    // Every reading maps onto Callout's three tones, none of which is reassuring — see Callout's
    // own note: reassurance here is the absence of a callout, not a friendlier one.
    const tones = new Set<string>()
    for (const probes of [healthy, notReady, allGone, someGone, strange, null]) {
      tones.add(read('https:', probes).tone)
    }
    tones.add(read('file:', null).tone)
    expect([...tones].sort()).toEqual(['critical', 'neutral', 'warn'])
  })
})

describe('the mail flag is restated and never elaborated', () => {
  it('reports both directions when /v1/config answered in its documented shape', () => {
    const off = read('https:', { ...healthy, capability: CONFIG_OFF })
    const on = read('https:', { ...healthy, capability: CONFIG_ON })
    expect(off.mail).toContain('will not send email')
    expect(on.mail).toContain('can send email')
    // The true branch is the one that has to hold its tongue: a setting, not an outcome.
    expect(on.mail).toContain('not a delivery')
  })

  it('says nothing at all when that endpoint did not answer in its documented shape', () => {
    expect(read('https:', { ...healthy, capability: PROXY_PAGE }).mail).toBeNull()
    expect(read('https:', { ...healthy, capability: GONE }).mail).toBeNull()
    expect(read('file:', null).mail).toBeNull()
    expect(read('https:', null).mail).toBeNull()
  })
})

describe('the sync question is left open rather than answered by a side effect', () => {
  it('is stated on every reading that involved a server, and is the same text every time', () => {
    // Constant text cannot leak a variable. This note is identical on every deployment, which is
    // precisely what makes it safe to name the setting in it.
    const notes = new Set<string | null>()
    for (const probes of [healthy, notReady, allGone, someGone, strange]) {
      notes.add(read('https:', probes).syncNote)
    }
    expect([...notes]).toEqual([SYNC_NOT_PROBED])
    expect(read('file:', null).syncNote).toBeNull()
    expect(read('https:', null).syncNote).toBeNull()
  })

  it('asserts neither direction: every mention of the state is governed by "whether"', () => {
    // The note has to be readable as "we did not ask" and not as "sync is off here" — which is a
    // fact about THIS deployment and is not this panel's to state. A flat string ban cannot express
    // that, because the sentence has to name the subject in order to decline to report it. So the
    // check is grammatical: every clause that predicates a configuration state must sit under a
    // "whether", which turns the assertion into a question.
    const CLAUSE =
      /[^.]*\b(?:is|is not|are|are not)\s+(?:set up|configured|enabled|switched on|switched off)\b[^.]*/gi

    // The detector fires on the sentence this exists to catch.
    const planted = [...'Sync is configured on this server. Ignore this.'.matchAll(CLAUSE)]
    expect(planted).toHaveLength(1)
    expect(planted[0]![0]).not.toMatch(/\bwhether\b/i)

    const clauses = [...SYNC_NOT_PROBED.matchAll(CLAUSE)].map((m) => m[0])
    expect(clauses.length, 'nothing to govern — the note stopped naming its subject').toBe(1)
    for (const c of clauses) expect(c, `ungoverned claim: ${c}`).toMatch(/\bwhether\b/i)

    expect(SYNC_NOT_PROBED).toContain('because it does not ask')
    expect(SYNC_NOT_PROBED).toContain('left open here')
  })

  it('names the setting and the documentation, without a value', () => {
    expect(SYNC_NOT_PROBED).toContain('DAYMARK_AUTH_TOKEN')
    expect(SYNC_NOT_PROBED).toContain('companion/README.md')
  })
})

describe('every line of advice says who it is addressed to', () => {
  it('labels each one, and the two audiences are named in words', () => {
    expect(AUDIENCE_LABEL.anyone).toBe('Anyone reading this')
    expect(AUDIENCE_LABEL.operator).toBe('Whoever runs this server')
    let lines = 0
    for (const probes of [healthy, notReady, allGone, someGone, strange]) {
      for (const l of read('https:', probes).lookHere) {
        expect(AUDIENCE_LABEL[l.audience]).toBeTruthy()
        expect(l.text.length).toBeGreaterThan(30)
        lines++
      }
    }
    expect(lines).toBeGreaterThanOrEqual(9)
  })

  it('addresses the operator with the env-var pointer, and everyone else with something they can do', () => {
    const r = read('https:', notReady)
    const operator = r.lookHere.filter((l) => l.audience === 'operator')
    const anyone = r.lookHere.filter((l) => l.audience === 'anyone')
    expect(operator).toHaveLength(1)
    expect(anyone).toHaveLength(1)
    expect(operator[0]!.text).toContain('DAYMARK_DATA_DIR')
    expect(operator[0]!.text).toContain('companion/README.md')
    expect(operator[0]!.text).toContain('server log')
    // …and the person who does not run the server is told that plainly rather than handed a chore.
    expect(anyone[0]!.text).toContain('If you do not run this server')
  })
})

/* ═══════════════════════════════════════════════════════════════════════════════════════════════
   THE DISCLOSURE RULE.
   ═══════════════════════════════════════════════════════════════════════════════════════════════ */

/**
 * Every subject the page is not allowed to disclose, each with a `fires` string proving the
 * detector works. The `fires` strings are what a careless version of this module would plausibly
 * have said — they are not adversarial nonsense, they are the sentences somebody would write while
 * trying to be helpful, which is the whole danger.
 */
const WITHHELD: { id: string; why: string; re: RegExp; fires: string }[] = [
  {
    id: 'trusted-proxy posture',
    why:
      'Telling a stranger that per-source controls share one bucket hands them the way to lock ' +
      'out every user of this server.',
    re: /trusted[\s_-]*prox|x-forwarded|forwarded[\s-]*(for|header)|\blockout\b|\blocked out\b|\brate[\s-]?limit|\bbucket\b/i,
    fires: 'DAYMARK_TRUSTED_PROXIES is unset, so every client shares one lockout bucket.',
  },
  {
    id: 'mail credentials and host',
    why: 'The flag is public; the host, the port and the credentials behind it are not.',
    re: /\bsmtp[\s_-]*(host|user|username|pass|password|port|credential|relay)\b|\bmail[\s-]*(host|server|relay)\b|DAYMARK_SMTP/i,
    fires: 'Set DAYMARK_SMTP_HOST to your mail server to enable invites.',
  },
  {
    id: 'any secret',
    why: 'The presence or absence of a secret is itself the disclosure.',
    re: /\bcredentials?\b|\bpasswords?\b|\bpassphrase\b|\bsecrets?\b|\bprivate key\b|\bapi key\b/i,
    fires: 'No credentials are configured on this server yet.',
  },
  {
    id: 'the data directory',
    why:
      'Its path, contents, size and free space are all withheld — and so is the shape of the ' +
      'failure, because /readyz deliberately does not say which one it is.',
    re: /(^|[^A-Z_])\/data\b|\bdisk\b|free space|\bbytes\b|read-only mount|permission denied|\b65532\b|\bchown\b|\bfilesystem\b|\bvolume\b|\bnot a directory\b/i,
    fires: 'Readiness failed: /data is not writable by uid 65532, or the disk is full.',
  },
  {
    id: 'an environment variable’s value',
    why: 'Never a value, in any state, for any variable.',
    re: /DAYMARK_[A-Z_]+\s*[=:]\s*\S/,
    fires: 'Currently DAYMARK_DATA_DIR=/srv/daymark/data',
  },
  {
    id: 'who the owner is, and whether relationships exist',
    why: 'None of this is an operations question and none of it is public.',
    re: /\brelationships?\b|\btherapists?\b|\bclinicians?\b|\bpatients?\b|\bclients?\b|\bowner\b|\binvites?\b|\binvitations?\b|\bhow many\b/i,
    fires: 'Sync is configured and 3 therapist relationships exist on this server.',
  },
  {
    id: 'a claim of health, safety or correctness',
    why:
      'This page sees three HTTP responses. It cannot know any of that, and a first-run screen is ' +
      'exactly where someone reaches for a tick and "All good!".',
    re: /\bhealthy\b|\bsecure\b|\bsafe\b|\ball (good|set|clear)\b|correctly configured|properly configured|\bverified\b|\bsuccess|\bpassed\b|✓|✔|✅|🟢|\bgreen\b/i,
    fires: 'All good — your server is healthy and correctly configured. ✅',
  },
  {
    id: 'a score, grade or percentage',
    why: 'Product rule: no score, percentage, grade, streak or shield, anywhere in this product.',
    re: /\d+\s?%|\bpercent\b|\bscore\b|\bgrade\b|\bstreak\b|\d+ *\/ *\d+ checks/i,
    fires: 'Configuration health: 2/3 checks passing (67%).',
  },
]

/**
 * Every authored string the module can emit, over an exhaustive matrix of inputs.
 *
 * Generated rather than listed. A constant that only appears on an odd combination of responses is
 * exactly the one a hand-written list forgets, and it is exactly the one written in a hurry.
 */
function corpus(): { where: string; text: string }[] {
  const shapes: Record<string, ProbeResponse> = {
    ok: OK_TRUE,
    refused: OK_FALSE_503,
    smtpOn: CONFIG_ON,
    smtpOff: CONFIG_OFF,
    gone: GONE,
    proxy: PROXY_PAGE,
    teapot: { kind: 'response', status: 418, body: '{"error":"sync API not configured"}' },
  }
  const out: { where: string; text: string }[] = []
  for (const [i, s] of STANDING_STRINGS.entries()) out.push({ where: `standing[${i}]`, text: s })

  for (const protocol of ['https:', 'http:', 'file:', '']) {
    out.push(
      ...authoredStrings(read(protocol, null)).map((text) => ({ where: `${protocol} null`, text })),
    )
    for (const [an, a] of Object.entries(shapes)) {
      for (const [bn, b] of Object.entries(shapes)) {
        for (const [cn, c] of Object.entries(shapes)) {
          const reading = read(protocol, { liveness: a, writability: b, capability: c })
          const where = `${protocol} ${an}/${bn}/${cn} → ${reading.id}`
          out.push(...authoredStrings(reading).map((text) => ({ where, text })))
        }
      }
    }
  }
  return out
}

describe('the disclosure rule holds over everything this module can say', () => {
  const all = corpus()

  it('the corpus is real, and covers every state', () => {
    // Non-vacuity, first. Without this the scan below could pass on an empty list forever.
    expect(all.length).toBeGreaterThan(2_000)
    const joined = all.map((e) => e.text).join('\n')
    // Sentences the module really ships. If the copy is rewritten these should be updated
    // deliberately; if the corpus collector broke, they vanish and this fails.
    expect(joined).toContain('carries no reason')
    expect(joined).toContain('Nothing on this screen contradicts a working setup')
    expect(joined).toContain('opened from a file on this device')
    expect(joined).toContain('DAYMARK_DATA_DIR')
    expect(joined).toContain('DAYMARK_AUTH_TOKEN')
    expect(joined).toContain('DAYMARK_BASE_PATH')
    // And every state's word really did make it in.
    for (const id of [
      'page-not-served',
      'not-checked',
      'no-answer',
      'partial-answer',
      'not-ready',
      'undocumented-answer',
      'answering',
    ] as ServerStateId[]) {
      const word = read(id === 'page-not-served' ? 'file:' : 'https:', null).word
      expect(word.length).toBeGreaterThan(0)
    }
    expect(joined).toContain('Answering')
    expect(joined).toContain('Not ready')
  })

  it('every detector fires on the sentence it exists to catch', () => {
    // The half that makes the next test mean something. Each `fires` string is a plausible,
    // well-intentioned sentence that this page must never contain.
    for (const w of WITHHELD) {
      expect(w.re.test(w.fires), `${w.id}: detector does not fire on its own example`).toBe(true)
    }
    // …and they are not "match everything" regexes: an ordinary sentence from the module passes.
    for (const w of WITHHELD) {
      expect(w.re.test('The process is up and routing requests.'), `${w.id}: over-broad`).toBe(false)
    }
  })

  it('names nothing that is withheld, in any state, for any combination of responses', () => {
    const hits: string[] = []
    for (const { where, text } of all) {
      for (const w of WITHHELD) {
        const m = w.re.exec(text)
        if (m) hits.push(`${w.id} — "${m[0]}" in ${where}: ${text.slice(0, 120)}`)
      }
    }
    expect(hits).toEqual([])
  })

  it('the fixed panel copy is in the scan too', () => {
    expect(STANDING_STRINGS).toContain(PANEL_LEDE)
    expect(STANDING_STRINGS).toContain(PANEL_FOOTER)
    expect(STANDING_STRINGS).toContain(SYNC_NOT_PROBED)
    expect(STANDING_STRINGS).toContain(BUSY_WORD)
    // The lede bounds what a reader may expect before they read a single row.
    expect(PANEL_LEDE).toContain('It is not a check of your setup')
    expect(PANEL_FOOTER).toContain('Every request behind this panel was unauthenticated')
  })
})

describe('bytes the module did not author are confined to one field', () => {
  it('keeps a hostile response body and error string out of every authored string', () => {
    // The containment proof, and the strongest evidence the scan above has teeth. Every withheld
    // subject at once, arriving from the wire. If authored copy and machine bytes were ever merged
    // into one field, these words would surface in `authoredStrings` and this fails loudly.
    const poison =
      'DAYMARK_TRUSTED_PROXIES= unset shared bucket lockout /data 65532 chown disk full ' +
      'permission denied DAYMARK_SMTP_HOST=mail.example.org password secret 3 therapist ' +
      'relationships owner healthy secure ✅ 67% score'
    const probes: ProbeSet = {
      liveness: { kind: 'transport', error: poison },
      writability: { kind: 'response', status: 500, body: poison },
      capability: { kind: 'response', status: 500, body: poison },
    }
    const r = read('https:', probes)

    // Presence half: the poison really did arrive, and really is on the page somewhere.
    const details = r.probes.map((p) => p.detail).filter((d): d is string => d !== null)
    expect(details).toHaveLength(3)
    expect(details.join(' ')).toContain('DAYMARK_TRUSTED_PROXIES')
    expect(details.join(' ')).toContain('65532')

    // Absence half: and it is confined to `detail`, which the corpus scan excludes by design —
    // these are bytes the caller already received from the origin that served this page, quoted
    // rather than paraphrased, and never blended into the module's own vocabulary.
    for (const text of authoredStrings(r)) {
      for (const w of WITHHELD) {
        expect(w.re.test(text), `${w.id} leaked into an authored string: ${text}`).toBe(false)
      }
    }
  })

  it('caps what it quotes, so an upstream page cannot take over the panel', () => {
    const huge = 'DAYMARK_TRUSTED_PROXIES '.repeat(500)
    const l = readProbeLine('liveness', { kind: 'response', status: 500, body: huge })
    expect(l.detail!.length).toBeLessThan(DETAIL_LIMIT + 40)
  })
})
